services:

    reverse-proxy:
        image: "jwilder/nginx-proxy:latest"
        container_name: "reverse-proxy"
        volumes:
            - "./data/html:/usr/share/nginx/html"
            - "./data/dhparam:/etc/nginx/dhparam"
            - "./data/vhost:/etc/nginx/vhost.d"
            - "./data/certs:/etc/nginx/certs"
            - "/run/docker.sock:/tmp/docker.sock:ro"
            - "./proxy.conf:/etc/nginx/conf.d/proxy.conf:ro"
        restart: "always"
        networks: 
            - "net"
        ports:
            - "80:80"
            - "443:443"
    letsencrypt:
        image: "jrcs/letsencrypt-nginx-proxy-companion:latest"
        container_name: "letsencrypt-helper"
        volumes:
            - "./data/html:/usr/share/nginx/html"
            - "./data/dhparam:/etc/nginx/dhparam"
            - "./data/vhost:/etc/nginx/vhost.d"
            - "./data/certs:/etc/nginx/certs"
            - "/run/docker.sock:/var/run/docker.sock:ro"
        env_file: .env
        restart: "always"
        depends_on:
            - "reverse-proxy"
        networks: 
            - "net"
networks:
  net:
    external: false
